/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErgebnisRouteImport } from './routes/ergebnis'
import { Route as RichtlinienRouteImport } from './routes/richtlinien'
import { Route as SkriptRouteImport } from './routes/skript'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgebnisRoute = ErgebnisRouteImport.update({
  id: '/ergebnis',
  path: '/ergebnis',
  getParentRoute: () => rootRouteImport,
} as any)
const RichtlinienRoute = RichtlinienRouteImport.update({
  id: '/richtlinien',
  path: '/richtlinien',
  getParentRoute: () => rootRouteImport,
} as any)
const SkriptRoute = SkriptRouteImport.update({
  id: '/skript',
  path: '/skript',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ergebnis': typeof ErgebnisRoute
  '/richtlinien': typeof RichtlinienRoute
  '/skript': typeof SkriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ergebnis': typeof ErgebnisRoute
  '/richtlinien': typeof RichtlinienRoute
  '/skript': typeof SkriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ergebnis': typeof ErgebnisRoute
  '/richtlinien': typeof RichtlinienRoute
  '/skript': typeof SkriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ergebnis' | '/richtlinien' | '/skript'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ergebnis' | '/richtlinien' | '/skript'
  id: '__root__' | '/' | '/ergebnis' | '/richtlinien' | '/skript'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErgebnisRoute: typeof ErgebnisRoute
  RichtlinienRoute: typeof RichtlinienRoute
  SkriptRoute: typeof SkriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergebnis': {
      id: '/ergebnis'
      path: '/ergebnis'
      fullPath: '/ergebnis'
      preLoaderRoute: typeof ErgebnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/richtlinien': {
      id: '/richtlinien'
      path: '/richtlinien'
      fullPath: '/richtlinien'
      preLoaderRoute: typeof RichtlinienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skript': {
      id: '/skript'
      path: '/skript'
      fullPath: '/skript'
      preLoaderRoute: typeof SkriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErgebnisRoute: ErgebnisRoute,
  RichtlinienRoute: RichtlinienRoute,
  SkriptRoute: SkriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
